// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqMLTXOaD0KoKKqVXyH8zXT_oqba1cJEE',
    appId: '1:295425507092:web:b255a507fa4828a4ffcc01',
    messagingSenderId: '295425507092',
    projectId: 'currencyconvertor-fceec',
    authDomain: 'currencyconvertor-fceec.firebaseapp.com',
    databaseURL: 'https://currencyconvertor-fceec-default-rtdb.firebaseio.com',
    storageBucket: 'currencyconvertor-fceec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOacagKe3lPA5u8G3YyiS-_YjIHiua-2g',
    appId: '1:295425507092:android:f6c1df589ea2b4b7ffcc01',
    messagingSenderId: '295425507092',
    projectId: 'currencyconvertor-fceec',
    databaseURL: 'https://currencyconvertor-fceec-default-rtdb.firebaseio.com',
    storageBucket: 'currencyconvertor-fceec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1psvDrgo7oBzH6ZxvMax9X6zPHS0b29s',
    appId: '1:295425507092:ios:43a07baf41d84fefffcc01',
    messagingSenderId: '295425507092',
    projectId: 'currencyconvertor-fceec',
    databaseURL: 'https://currencyconvertor-fceec-default-rtdb.firebaseio.com',
    storageBucket: 'currencyconvertor-fceec.appspot.com',
    iosBundleId: 'com.example.currencyConversion',
  );
}
